apiVersion: v1
kind: Pod
metadata:
  name: didi-mysql-pod
  creationTimestamp: null
  labels: 
  run: mysql
name: mysql
spec:
  containers:
      - image: mysql:5.7
        name: mysql
        ports:
          - containerPort: 3306
            protocol: "TCP"
        env:
          - name: MYSQL_DATABASE
            value: "exampledb"
            name: MYSQL_USER
            value: "exampleuser"
            name: MYSQL_PASSWORD
            value: "examplepass"
            name: MYSQL_RANDOM_ROOT_PASSWORD
            value: "1"
            name: MYSQL_RANDOM_ROOT_PASSWORD
            value: "1"
        resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  status: {}