apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels: 
    run: mysql
  name: mysql
spec:
  ports: 
    - port: 8080
      protocol: TCP
      targetPort: 80 # EN EL CONTENEDOR 
  type: NodePort
  selector: 
    run: wordpress
status:
  loadBalancer: {}